---

- name: Set timezone
  community.general.timezone:
    name: US/Pacific

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
    use: systemd

- name: Add k8s apt key
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_major }}/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add k8s apt repos
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ k8s_version_major }}/deb/ /
    state: present

- name: Add Docker repos keys
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add Docker apt repo
  ansible.builtin.apt_repository:
    repo: deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    state: present

- name: Install common packages
  ansible.builtin.apt:
    state: present
    update_cache: true
    pkg:
      - kubectl={{ k8s_version }}
      - kubeadm={{ k8s_version }}
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io={{ containerd_version }}
      - stress-ng

- name: Configure kubernetes networking
  ansible.posix.sysctl:
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop:
    - { name: 'net.ipv4.ip_forward', value: '1'}
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1'}
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1'}

- name: Enable CRI driver for containerd
  ansible.builtin.lineinfile:
    path: /etc/containerd/config.toml
    state: absent
    line: disabled_plugins = ["cri"]
  notify:
    - Restart containerd

- name: Disable systemd swap
  ansible.builtin.systemd_service:
    name: swapfile.swap
    masked: true

- name: Disable swap
  ansible.builtin.command:
    cmd: swapoff -a
  when: ansible_swaptotal_mb > 0
  register: swapoff_result
  changed_when: swapoff_result.rc == 0

- name: Create bin dir
  ansible.builtin.file:
    path: /home/ubuntu/bin
    state: directory
    mode: "0755"
    owner: ubuntu
